affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  DB_HOST: mysql-backend.backend.svc.cluster.local
  DB_NAME: devopsdb
  DB_PASSWORD: devpass123
  DB_USER: devuser
  ENV_NAME: dev
fullnameOverride: ''
httpRoute:
  annotations: {}
  enabled: false
  hostnames:
  - chart-example.local
  parentRefs:
  - name: gateway
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
image:
  pullPolicy: IfNotPresent
  repository: narendra7306/php-app
  tag: v59.0.0
imagePullSecrets:
- name: dockerhub-secret
ingress:
  annotations: {}
  className: nginx
  enabled: true
  hosts:
  - host: app.example.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - app.example.com
    secretName: chart-example-tls
livenessProbe: null
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe: null
replicaCount: 1
resources: {}
securityContext: {}
service:
  name: php
  port: 80
  protocol: TCP
  targetPort: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''
tolerations: []
volumeMounts: []
volumes: []
