FROM mysql:8.0

# Set environment variables

ENV MYSQL_DATABASE=devopsdb

RUN microdnf update -y && microdnf upgrade -y && microdnf clean all


# Copy the SQL file into the container's init folder
COPY backup.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306
