FROM ubuntu/mysql:8.0-24.04_edge

# Set environment variables

ENV MYSQL_DATABASE=devopsdb

RUN apt-get update -y && apt-get upgrade -y && apt-get clean

# Copy the SQL file into the container's init folder
COPY backup.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306
