affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  MYSQL_DATABASE: devopsdb
  MYSQL_PASSWORD: devpass123
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: devuser
extraContainers:
- env:
  - name: DATA_SOURCE_NAME
    value: exporter:exporter123@(127.0.0.1:3306)/
  image: prom/mysqld-exporter:v0.14.0
  name: mysqld-exporter
  ports:
  - containerPort: 9104
    name: metrics
extraServices:
- name: mysql-metrics
  ports:
  - name: metrics
    port: 9104
    targetPort: metrics
fullnameOverride: ''
httpRoute:
  annotations: {}
  enabled: false
  hostnames:
  - chart-example.local
  parentRefs:
  - name: gateway
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
image:
  pullPolicy: IfNotPresent
  repository: narendra7306/mysql-backend
  tag: v48.0.0
imagePullSecrets: []
ingress:
  annotations: {}
  className: ''
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
livenessProbe: null
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels:
  app: mysql-metrics
podSecurityContext: {}
readinessProbe: null
replicaCount: 1
resources: {}
securityContext: {}
service:
  name: mysql
  port: 3306
  protocol: TCP
  targetPort: 3306
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''
tolerations: []
volumeMounts: []
volumes: []
